name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          package-name: intopdf
          filename: example/intopdf.tar.gz
          version: v0.4.0
          author: Invalid Author
          uploader: Unknown Uploader
          email: invalid@example.com
          ctan-path: /macros/latex/contrib/intopdf
          summary: Include files in PDF
          license: lppl
          description: |
            Some longer description,
            going over multiple lines.
          update: true
          dry-run: true
          repository: https://github.com/zauguin/intopdf
          bugtracker: https://github.com/zauguin/intopdf/issues
